/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Country extends org.jooq.impl.TableImpl<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord> {

	private static final long serialVersionUID = -201615075;

	/**
	 * The reference instance of <code>PUBLIC.COUNTRY</code>
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.Country COUNTRY = new com.fhoster.jooq4hibernate.jooq.tables.Country();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord> getRecordType() {
		return com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord.class;
	}

	/**
	 * The column <code>PUBLIC.COUNTRY.ID_COUNTRY</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord, java.lang.Long> ID_COUNTRY = createField("ID_COUNTRY", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.COUNTRY.NAME</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.COUNTRY.ID_CAPITAL_CITY</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord, java.lang.Long> ID_CAPITAL_CITY = createField("ID_CAPITAL_CITY", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>PUBLIC.COUNTRY</code> table reference
	 */
	public Country() {
		this("COUNTRY", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.COUNTRY</code> table reference
	 */
	public Country(java.lang.String alias) {
		this(alias, com.fhoster.jooq4hibernate.jooq.tables.Country.COUNTRY);
	}

	private Country(java.lang.String alias, org.jooq.Table<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Country(java.lang.String alias, org.jooq.Table<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.fhoster.jooq4hibernate.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord> getPrimaryKey() {
		return com.fhoster.jooq4hibernate.jooq.Keys.SYS_PK_10106;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord>>asList(com.fhoster.jooq4hibernate.jooq.Keys.SYS_PK_10106);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.fhoster.jooq4hibernate.jooq.tables.records.CountryRecord, ?>>asList(com.fhoster.jooq4hibernate.jooq.Keys.FK_CVYAV791OGVBOFSWRJKD4CNNI);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.fhoster.jooq4hibernate.jooq.tables.Country as(java.lang.String alias) {
		return new com.fhoster.jooq4hibernate.jooq.tables.Country(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.fhoster.jooq4hibernate.jooq.tables.Country rename(java.lang.String name) {
		return new com.fhoster.jooq4hibernate.jooq.tables.Country(name, null);
	}
}
