/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee extends org.jooq.impl.TableImpl<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord> {

	private static final long serialVersionUID = 108945667;

	/**
	 * The reference instance of <code>PUBLIC.EMPLOYEE</code>
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.Employee EMPLOYEE = new com.fhoster.jooq4hibernate.jooq.tables.Employee();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord> getRecordType() {
		return com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord.class;
	}

	/**
	 * The column <code>PUBLIC.EMPLOYEE.ID_EMPLOYEE</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord, java.lang.Long> ID_EMPLOYEE = createField("ID_EMPLOYEE", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.EMPLOYEE.FIRSTNAME</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord, java.lang.String> FIRSTNAME = createField("FIRSTNAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.EMPLOYEE.LASTNAME</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord, java.lang.String> LASTNAME = createField("LASTNAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.EMPLOYEE.CURRENT_ADDRESS_ID</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord, java.lang.Long> CURRENT_ADDRESS_ID = createField("CURRENT_ADDRESS_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>PUBLIC.EMPLOYEE.PERMANENT_ADDRESS_ID</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord, java.lang.Long> PERMANENT_ADDRESS_ID = createField("PERMANENT_ADDRESS_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>PUBLIC.EMPLOYEE</code> table reference
	 */
	public Employee() {
		this("EMPLOYEE", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.EMPLOYEE</code> table reference
	 */
	public Employee(java.lang.String alias) {
		this(alias, com.fhoster.jooq4hibernate.jooq.tables.Employee.EMPLOYEE);
	}

	private Employee(java.lang.String alias, org.jooq.Table<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Employee(java.lang.String alias, org.jooq.Table<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.fhoster.jooq4hibernate.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord> getPrimaryKey() {
		return com.fhoster.jooq4hibernate.jooq.Keys.SYS_PK_10112;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord>>asList(com.fhoster.jooq4hibernate.jooq.Keys.SYS_PK_10112);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.fhoster.jooq4hibernate.jooq.tables.records.EmployeeRecord, ?>>asList(com.fhoster.jooq4hibernate.jooq.Keys.FK_LOGKCVDAEE6XYWV5LSL9M1J2J, com.fhoster.jooq4hibernate.jooq.Keys.FK_HM0G01YK4OF86MK55MGXNPYWD);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.fhoster.jooq4hibernate.jooq.tables.Employee as(java.lang.String alias) {
		return new com.fhoster.jooq4hibernate.jooq.tables.Employee(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.fhoster.jooq4hibernate.jooq.tables.Employee rename(java.lang.String name) {
		return new com.fhoster.jooq4hibernate.jooq.tables.Employee(name, null);
	}
}
