/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OfficeAddress extends org.jooq.impl.TableImpl<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord> {

	private static final long serialVersionUID = -647653309;

	/**
	 * The reference instance of <code>PUBLIC.OFFICE_ADDRESS</code>
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress OFFICE_ADDRESS = new com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord> getRecordType() {
		return com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord.class;
	}

	/**
	 * The column <code>PUBLIC.OFFICE_ADDRESS.ID_COMPANY</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord, java.lang.Long> ID_COMPANY = createField("ID_COMPANY", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.OFFICE_ADDRESS.ID_ADDRESS</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord, java.lang.Long> ID_ADDRESS = createField("ID_ADDRESS", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.OFFICE_ADDRESS</code> table reference
	 */
	public OfficeAddress() {
		this("OFFICE_ADDRESS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.OFFICE_ADDRESS</code> table reference
	 */
	public OfficeAddress(java.lang.String alias) {
		this(alias, com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress.OFFICE_ADDRESS);
	}

	private OfficeAddress(java.lang.String alias, org.jooq.Table<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord> aliased) {
		this(alias, aliased, null);
	}

	private OfficeAddress(java.lang.String alias, org.jooq.Table<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.fhoster.jooq4hibernate.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord> getPrimaryKey() {
		return com.fhoster.jooq4hibernate.jooq.Keys.SYS_PK_10121;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord>>asList(com.fhoster.jooq4hibernate.jooq.Keys.SYS_PK_10121);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.fhoster.jooq4hibernate.jooq.tables.records.OfficeAddressRecord, ?>>asList(com.fhoster.jooq4hibernate.jooq.Keys.FK_AYGTTOKBEMI0CHL7SI9HQ000, com.fhoster.jooq4hibernate.jooq.Keys.FK_KM9TXALYXQBMSPXT0P3UKINVM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress as(java.lang.String alias) {
		return new com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress rename(java.lang.String name) {
		return new com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress(name, null);
	}
}
