/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class State extends org.jooq.impl.TableImpl<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord> {

	private static final long serialVersionUID = 1208067016;

	/**
	 * The reference instance of <code>PUBLIC.STATE</code>
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.State STATE = new com.fhoster.jooq4hibernate.jooq.tables.State();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord> getRecordType() {
		return com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord.class;
	}

	/**
	 * The column <code>PUBLIC.STATE.ID_STATE</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord, java.lang.Long> ID_STATE = createField("ID_STATE", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.STATE.NAME</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.STATE.ID_COUNTRY</code>.
	 */
	public final org.jooq.TableField<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord, java.lang.Long> ID_COUNTRY = createField("ID_COUNTRY", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>PUBLIC.STATE</code> table reference
	 */
	public State() {
		this("STATE", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.STATE</code> table reference
	 */
	public State(java.lang.String alias) {
		this(alias, com.fhoster.jooq4hibernate.jooq.tables.State.STATE);
	}

	private State(java.lang.String alias, org.jooq.Table<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord> aliased) {
		this(alias, aliased, null);
	}

	private State(java.lang.String alias, org.jooq.Table<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.fhoster.jooq4hibernate.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord> getPrimaryKey() {
		return com.fhoster.jooq4hibernate.jooq.Keys.SYS_PK_10130;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord>>asList(com.fhoster.jooq4hibernate.jooq.Keys.SYS_PK_10130);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord, ?>>asList(com.fhoster.jooq4hibernate.jooq.Keys.FK_MNLCLB4B80OSPHGASBDMDWOKG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.fhoster.jooq4hibernate.jooq.tables.State as(java.lang.String alias) {
		return new com.fhoster.jooq4hibernate.jooq.tables.State(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.fhoster.jooq4hibernate.jooq.tables.State rename(java.lang.String name) {
		return new com.fhoster.jooq4hibernate.jooq.tables.State(name, null);
	}
}
