/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1015936904;

	/**
	 * The reference instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.fhoster.jooq4hibernate.jooq.tables.Address.ADDRESS,
			com.fhoster.jooq4hibernate.jooq.tables.City.CITY,
			com.fhoster.jooq4hibernate.jooq.tables.Company.COMPANY,
			com.fhoster.jooq4hibernate.jooq.tables.Country.COUNTRY,
			com.fhoster.jooq4hibernate.jooq.tables.Employee.EMPLOYEE,
			com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress.OFFICE_ADDRESS,
			com.fhoster.jooq4hibernate.jooq.tables.State.STATE);
	}
}
