/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq;

/**
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.ADDRESS
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.Address ADDRESS = com.fhoster.jooq4hibernate.jooq.tables.Address.ADDRESS;

	/**
	 * The table PUBLIC.CITY
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.City CITY = com.fhoster.jooq4hibernate.jooq.tables.City.CITY;

	/**
	 * The table PUBLIC.COMPANY
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.Company COMPANY = com.fhoster.jooq4hibernate.jooq.tables.Company.COMPANY;

	/**
	 * The table PUBLIC.COUNTRY
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.Country COUNTRY = com.fhoster.jooq4hibernate.jooq.tables.Country.COUNTRY;

	/**
	 * The table PUBLIC.EMPLOYEE
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.Employee EMPLOYEE = com.fhoster.jooq4hibernate.jooq.tables.Employee.EMPLOYEE;

	/**
	 * The table PUBLIC.OFFICE_ADDRESS
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress OFFICE_ADDRESS = com.fhoster.jooq4hibernate.jooq.tables.OfficeAddress.OFFICE_ADDRESS;

	/**
	 * The table PUBLIC.STATE
	 */
	public static final com.fhoster.jooq4hibernate.jooq.tables.State STATE = com.fhoster.jooq4hibernate.jooq.tables.State.STATE;
}
