/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends org.jooq.impl.UpdatableRecordImpl<com.fhoster.jooq4hibernate.jooq.tables.records.AddressRecord> implements org.jooq.Record4<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -728539074;

	/**
	 * Setter for <code>PUBLIC.ADDRESS.ID_ADDRESS</code>.
	 */
	public void setIdAddress(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.ADDRESS.ID_ADDRESS</code>.
	 */
	public java.lang.Long getIdAddress() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.ADDRESS.NUMBER</code>.
	 */
	public void setNumber(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.ADDRESS.NUMBER</code>.
	 */
	public java.lang.Integer getNumber() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.ADDRESS.STREET</code>.
	 */
	public void setStreet(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.ADDRESS.STREET</code>.
	 */
	public java.lang.String getStreet() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.ADDRESS.ID_CITY</code>.
	 */
	public void setIdCity(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.ADDRESS.ID_CITY</code>.
	 */
	public java.lang.Long getIdCity() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.fhoster.jooq4hibernate.jooq.tables.Address.ADDRESS.ID_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.fhoster.jooq4hibernate.jooq.tables.Address.ADDRESS.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.fhoster.jooq4hibernate.jooq.tables.Address.ADDRESS.STREET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.fhoster.jooq4hibernate.jooq.tables.Address.ADDRESS.ID_CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getIdAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getStreet();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getIdCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value1(java.lang.Long value) {
		setIdAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value2(java.lang.Integer value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value3(java.lang.String value) {
		setStreet(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value4(java.lang.Long value) {
		setIdCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.String value3, java.lang.Long value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AddressRecord
	 */
	public AddressRecord() {
		super(com.fhoster.jooq4hibernate.jooq.tables.Address.ADDRESS);
	}

	/**
	 * Create a detached, initialised AddressRecord
	 */
	public AddressRecord(java.lang.Long idAddress, java.lang.Integer number, java.lang.String street, java.lang.Long idCity) {
		super(com.fhoster.jooq4hibernate.jooq.tables.Address.ADDRESS);

		setValue(0, idAddress);
		setValue(1, number);
		setValue(2, street);
		setValue(3, idCity);
	}
}
