/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityRecord extends org.jooq.impl.UpdatableRecordImpl<com.fhoster.jooq4hibernate.jooq.tables.records.CityRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -294376486;

	/**
	 * Setter for <code>PUBLIC.CITY.ID_CITY</code>.
	 */
	public void setIdCity(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.CITY.ID_CITY</code>.
	 */
	public java.lang.Long getIdCity() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.CITY.NAME</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.CITY.NAME</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.CITY.ID_STATE</code>.
	 */
	public void setIdState(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.CITY.ID_STATE</code>.
	 */
	public java.lang.Long getIdState() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.fhoster.jooq4hibernate.jooq.tables.City.CITY.ID_CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.fhoster.jooq4hibernate.jooq.tables.City.CITY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.fhoster.jooq4hibernate.jooq.tables.City.CITY.ID_STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getIdCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getIdState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CityRecord value1(java.lang.Long value) {
		setIdCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CityRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CityRecord value3(java.lang.Long value) {
		setIdState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CityRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CityRecord
	 */
	public CityRecord() {
		super(com.fhoster.jooq4hibernate.jooq.tables.City.CITY);
	}

	/**
	 * Create a detached, initialised CityRecord
	 */
	public CityRecord(java.lang.Long idCity, java.lang.String name, java.lang.Long idState) {
		super(com.fhoster.jooq4hibernate.jooq.tables.City.CITY);

		setValue(0, idCity);
		setValue(1, name);
		setValue(2, idState);
	}
}
