/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends org.jooq.impl.UpdatableRecordImpl<com.fhoster.jooq4hibernate.jooq.tables.records.CompanyRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -2076399409;

	/**
	 * Setter for <code>PUBLIC.COMPANY.ID_COMPANY</code>.
	 */
	public void setIdCompany(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMPANY.ID_COMPANY</code>.
	 */
	public java.lang.Long getIdCompany() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.COMPANY.NAME</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMPANY.NAME</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.COMPANY.ID_HEAD_OFFICE_ADDRESS</code>.
	 */
	public void setIdHeadOfficeAddress(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMPANY.ID_HEAD_OFFICE_ADDRESS</code>.
	 */
	public java.lang.Long getIdHeadOfficeAddress() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.fhoster.jooq4hibernate.jooq.tables.Company.COMPANY.ID_COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.fhoster.jooq4hibernate.jooq.tables.Company.COMPANY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.fhoster.jooq4hibernate.jooq.tables.Company.COMPANY.ID_HEAD_OFFICE_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getIdCompany();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getIdHeadOfficeAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value1(java.lang.Long value) {
		setIdCompany(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value3(java.lang.Long value) {
		setIdHeadOfficeAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CompanyRecord
	 */
	public CompanyRecord() {
		super(com.fhoster.jooq4hibernate.jooq.tables.Company.COMPANY);
	}

	/**
	 * Create a detached, initialised CompanyRecord
	 */
	public CompanyRecord(java.lang.Long idCompany, java.lang.String name, java.lang.Long idHeadOfficeAddress) {
		super(com.fhoster.jooq4hibernate.jooq.tables.Company.COMPANY);

		setValue(0, idCompany);
		setValue(1, name);
		setValue(2, idHeadOfficeAddress);
	}
}
