/**
 * This class is generated by jOOQ
 */
package com.fhoster.jooq4hibernate.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StateRecord extends org.jooq.impl.UpdatableRecordImpl<com.fhoster.jooq4hibernate.jooq.tables.records.StateRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -1866121111;

	/**
	 * Setter for <code>PUBLIC.STATE.ID_STATE</code>.
	 */
	public void setIdState(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.STATE.ID_STATE</code>.
	 */
	public java.lang.Long getIdState() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.STATE.NAME</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.STATE.NAME</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.STATE.ID_COUNTRY</code>.
	 */
	public void setIdCountry(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.STATE.ID_COUNTRY</code>.
	 */
	public java.lang.Long getIdCountry() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.fhoster.jooq4hibernate.jooq.tables.State.STATE.ID_STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.fhoster.jooq4hibernate.jooq.tables.State.STATE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.fhoster.jooq4hibernate.jooq.tables.State.STATE.ID_COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getIdState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getIdCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StateRecord value1(java.lang.Long value) {
		setIdState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StateRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StateRecord value3(java.lang.Long value) {
		setIdCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StateRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StateRecord
	 */
	public StateRecord() {
		super(com.fhoster.jooq4hibernate.jooq.tables.State.STATE);
	}

	/**
	 * Create a detached, initialised StateRecord
	 */
	public StateRecord(java.lang.Long idState, java.lang.String name, java.lang.Long idCountry) {
		super(com.fhoster.jooq4hibernate.jooq.tables.State.STATE);

		setValue(0, idState);
		setValue(1, name);
		setValue(2, idCountry);
	}
}
